"""
database/hyderabad_places.py

A small, hand-curated offline dataset of Hyderabad attractions/food spots.
No network/API calls -- this is the "local database" the recommendation
engine searches against, keeping the whole pipeline offline.
"""

PLACES = [
    {
        "name": "Charminar",
        "category": "place",
        "tags": ["history", "architecture", "iconic", "photography"],
        "near": ["Laad Bazaar", "Chowmahalla Palace", "Mecca Masjid"],
        "avg_cost": 0,
        "duration_minutes": 60,
        "lat": 17.3616, "lng": 78.4747,
    },
    {
        "name": "Laad Bazaar",
        "category": "shopping",
        "tags": ["shopping", "bangles", "culture"],
        "near": ["Charminar"],
        "avg_cost": 500,
        "duration_minutes": 90,
        "lat": 17.3604, "lng": 78.4736,
    },
    {
        "name": "Chowmahalla Palace",
        "category": "place",
        "tags": ["history", "architecture", "photography"],
        "near": ["Charminar"],
        "avg_cost": 100,
        "duration_minutes": 90,
        "lat": 17.3580, "lng": 78.4738,
    },
    {
        "name": "Golconda Fort",
        "category": "place",
        "tags": ["history", "architecture", "trekking", "photography"],
        "near": ["Qutb Shahi Tombs"],
        "avg_cost": 50,
        "duration_minutes": 150,
        "lat": 17.3833, "lng": 78.4011,
    },
    {
        "name": "Qutb Shahi Tombs",
        "category": "place",
        "tags": ["history", "architecture"],
        "near": ["Golconda Fort"],
        "avg_cost": 25,
        "duration_minutes": 60,
        "lat": 17.3911, "lng": 78.3956,
    },
    {
        "name": "Hussain Sagar",
        "category": "place",
        "tags": ["nature", "boating", "photography", "nightlife"],
        "near": ["Necklace Road", "Birla Mandir"],
        "avg_cost": 100,
        "duration_minutes": 90,
        "lat": 17.4239, "lng": 78.4738,
    },
    {
        "name": "Necklace Road",
        "category": "place",
        "tags": ["nature", "nightlife", "photography"],
        "near": ["Hussain Sagar"],
        "avg_cost": 0,
        "duration_minutes": 60,
        "lat": 17.4260, "lng": 78.4690,
    },
    {
        "name": "Birla Mandir",
        "category": "place",
        "tags": ["history", "architecture", "culture"],
        "near": ["Hussain Sagar"],
        "avg_cost": 0,
        "duration_minutes": 45,
        "lat": 17.4062, "lng": 78.4691,
    },
    {
        "name": "Salar Jung Museum",
        "category": "place",
        "tags": ["history", "art", "culture"],
        "near": ["Charminar"],
        "avg_cost": 50,
        "duration_minutes": 120,
        "lat": 17.3713, "lng": 78.4804,
    },
    {
        "name": "Ramoji Film City",
        "category": "place",
        "tags": ["entertainment", "family", "photography"],
        "near": [],
        "avg_cost": 1200,
        "duration_minutes": 360,
        "lat": 17.2543, "lng": 78.6808,
    },
    {
        "name": "Shilparamam",
        "category": "place",
        "tags": ["art", "culture", "shopping"],
        "near": [],
        "avg_cost": 100,
        "duration_minutes": 90,
        "lat": 17.4533, "lng": 78.3713,
    },
    {
        "name": "Snow World",
        "category": "place",
        "tags": ["entertainment", "family"],
        "near": [],
        "avg_cost": 600,
        "duration_minutes": 90,
        "lat": 17.4239, "lng": 78.4528,
    },
    {
        "name": "Hotel Shadab",
        "category": "food",
        "tags": ["biryani", "haleem", "kebabs"],
        "near": ["Charminar"],
        "avg_cost": 300,
        "duration_minutes": 60,
        "lat": 17.3622, "lng": 78.4750,
    },
    {
        "name": "Bawarchi",
        "category": "food",
        "tags": ["biryani"],
        "near": [],
        "avg_cost": 350,
        "duration_minutes": 60,
        "lat": 17.4012, "lng": 78.4982,
    },
    {
        "name": "Paradise Restaurant",
        "category": "food",
        "tags": ["biryani", "kebabs"],
        "near": [],
        "avg_cost": 400,
        "duration_minutes": 60,
        "lat": 17.4400, "lng": 78.4914,
    },
    {
        "name": "Pista House",
        "category": "food",
        "tags": ["haleem", "sweets"],
        "near": ["Charminar"],
        "avg_cost": 200,
        "duration_minutes": 30,
        "lat": 17.3651, "lng": 78.4744,
    },
]
